### ISSUE TITLE
Official documentation

### ISSUE THREAD

**Issue by deftk** [TKFRvisionOfficial/lernsax-webweaver-api-research#2]
Hi,
this repository seems a bit disbanned, but if you are still interested, there is official documentation of the API available. You just have to append "/wws/559185.php" to the base url of your WebWeaver provider, so in this case it would be https://www.lernsax.de/wws/559185.php. This works with other providers too, like wwschool.

I already wrote a partial API wrapper in Kotlin, but I found your repository and thought you might be interested in the documentation. Have a nice day :)

**Comment by TKFRvisionOfficial** [comment]
HAHAHAHAHA. Thanks so much dude. You're the man!!!!!
